name: tb_flutter_toolkit
description: "A set of custom Flutter UI components."
version: 0.1.2
homepage: https://github.com/tangbing/tb_flutter_toolkit.git
repository: https://github.com/tangbing/tb_flutter_toolkit.git

environment:
  sdk: ^3.4.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.15.0
#  image_gallery_saver: "^2.0.3"
  cached_network_image: any
  gal: ^2.3.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  wechat_assets_picker: ^9.5.0
  wechat_camera_picker: ^4.3.7








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
